spring:
  datasource:
    url: jdbc:derby:memory:paises;create=true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyTenSevenDialect
        show-sql: true